### ISSUE TITLE
AO-RTSP sink JSON dump error

### ISSUE THREAD

**Issue by abramov-oleg** [insight-platform/Savant#268]
AO-RTSP sink encounters error while trying to dump metadata as JSON.

To reproduce, run the sink  with env var `METADATA_OUTPUT=stdout` or `METADATA_OUTPUT=logger`.

Container prints error logs

```
Traceback (most recent call last):
nvidia_car_classification-always-on-sink-1     |   File "/opt/savant/adapters/ds/sinks/always_on_rtsp/__main__.py", line 105, in log_frame_metadata
nvidia_car_classification-always-on-sink-1     |     metadata_json = json.dumps(asdict(metadata))
nvidia_car_classification-always-on-sink-1     |   File "/usr/lib/python3.8/json/__init__.py", line 231, in dumps
nvidia_car_classification-always-on-sink-1     |     return _default_encoder.encode(obj)
nvidia_car_classification-always-on-sink-1     |   File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
nvidia_car_classification-always-on-sink-1     |     chunks = self.iterencode(o, _one_shot=True)
nvidia_car_classification-always-on-sink-1     |   File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
nvidia_car_classification-always-on-sink-1     |     return _iterencode(o, 0)
nvidia_car_classification-always-on-sink-1     |   File "/usr/lib/python3.8/json/encoder.py", line 179, in default
nvidia_car_classification-always-on-sink-1     |     raise TypeError(f'Object of type {o.__class__.__name__} '
nvidia_car_classification-always-on-sink-1     | TypeError: Object of type OnlyExtendedDict is not JSON serializable
```

**Comment by tomskikh** [comment]
`json-sink` doesn't have `command: python -m adapters.python.sinks.metadata_json` in compose file for develop branch.

**Comment by abramov-oleg** [comment]
Another JSON dump error, this time with AO-sink. Manifests when the sink is run with env var `METADATA_OUTPUT=stdout` or `METADATA_OUTPUT=logger`

Container prints error logs

```
Traceback (most recent call last):
nvidia_car_classification-always-on-sink-1     |   File "/opt/savant/adapters/ds/sinks/always_on_rtsp/__main__.py", line 105, in log_frame_metadata
nvidia_car_classification-always-on-sink-1     |     metadata_json = json.dumps(asdict(metadata))
nvidia_car_classification-always-on-sink-1     |   File "/usr/lib/python3.8/json/__init__.py", line 231, in dumps
nvidia_car_classification-always-on-sink-1     |     return _default_encoder.encode(obj)
nvidia_car_classification-always-on-sink-1     |   File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
nvidia_car_classification-always-on-sink-1     |     chunks = self.iterencode(o, _one_shot=True)
nvidia_car_classification-always-on-sink-1     |   File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
nvidia_car_classification-always-on-sink-1     |     return _iterencode(o, 0)
nvidia_car_classification-always-on-sink-1     |   File "/usr/lib/python3.8/json/encoder.py", line 179, in default
nvidia_car_classification-always-on-sink-1     |     raise TypeError(f'Object of type {o.__class__.__name__} '
nvidia_car_classification-always-on-sink-1     | TypeError: Object of type OnlyExtendedDict is not JSON serializable
```

Can be relevant?

**Comment by tomskikh** [comment]
@abramov-oleg No, this is irrelevant to the issue.
