### ISSUE TITLE
Face ReID demo preprocessor exception

### ISSUE THREAD

**Issue by denisvmedyantsev** [insight-platform/Savant#465]
The error does not always occur and only when using a multistream source adapter and a module primary batch size of 4 or 8
```
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/savant/gstreamer/buffer_processor.py", line 86, in element_input_probe
self.prepare_element_input(element, buffer)
File "/usr/local/lib/python3.8/dist-packages/savant/deepstream/buffer_processor.py", line 520, in prepare_element_input
self._objects_preprocessing.preprocessing(
File "/usr/local/lib/python3.8/dist-packages/savant/base/input_preproc.py", line 134, in preprocessing
raise exc
File "/usr/local/lib/python3.8/dist-packages/savant/base/input_preproc.py", line 122, in preprocessing
preprocess_image = preprocessing_func(
File "/usr/local/lib/python3.8/dist-packages/savant/base/pyfunc.py", line 268, in __call__
return self._callable(*args, **kwargs)
File "/opt/savant/samples/face_reid/face_preproc.py", line 37, in __call__
landmarks = object_meta.get_attr_meta(
AttributeError: 'NoneType' object has no attribute 'value'
```

**Comment by denisvmedyantsev** [comment]
The problem is caused by objects added by the nvtracker. Such objects don't have landmarks. It is strange that the problem is so rare and was detected only in this demo and with multistream. The nvtracker does not have a setting that suppresses object creation. We can 
1) patch the nvtracker;
2) add a postprocessor right after the nvtracker and remove created objects (using a pad probe or make a bin);
3) keep in mind the possibility of incomplete (without attributes and correct parent) objects appearing in the meta and check everywhere when accessing objects;
4) separate face detection and landmark detection into 2 models

**Comment by bwsw** [comment]
@denisvmedyantsev let us go with (iii) for now.
